---
    title: 
        ru: Лучше уж не в золотой клетке
        en: Better not in a golden cage
        common: Лучше уж не в золотой клетке
        
    description: 
        ru: "Что, если бы Николай изначально делал всё по другому? Если бы он нашёл задатки спутницы жизни первоначально в Эли и стремился исключительно к своему счастью, даже не осознавая этого? Именно в этом фанфике и повествуется такая история."
        en: "No ENG version (yet)"
        common: "No ENG version (yet)"
        
    version: 0.3.2
    cover: сover.jpg