---
  title: 
    ru: Лучше уж не в золотой клетке
    en: Better not in a golden cage
    common: Лучше уж не в золотой клетке
        
  description: 
    ru: "Что, если бы Николай изначально делал всё по другому? Если бы он нашёл задатки спутницы жизни первоначально в Эли и стремился исключительно к своему счастью, даже не осознавая этого? Именно в этом фанфике и повествуется такая история."
    en: "What if Nikolai had originally done everything differently? If he had found the makings of a life partner initially in Eli and was striving exclusively for his happiness without even realizing it? It is in this fan fiction that such a story is told."
    common: "Что, если бы Николай изначально делал всё по другому? Если бы он нашёл задатки спутницы жизни первоначально в Эли и стремился исключительно к своему счастью, даже не осознавая этого? Именно в этом фанфике и повествуется такая история."
        
  version: 0.5.0
  cover: сover.jpg